import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(general)/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: {
        default: "Si-Mas Kuli",
        template: "%s | Si-Mas Kuli",
    },
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
